function [relPose, score, covariance] = matchScansGrid(currentScan, referenceScan, ...
                                                      initialPoseAvailable, ...
                                                      initialPose, ...
                                                      maxRange, ...
                                                      resolution, ...
                                                      linSearchRange, ...
                                                      angSearchRange, ...
                                                      maxLevel, computeCov)
    %This function is for internal use only. It may be removed in the future.

    %matchScansGrid Match two scans using a grid-based search

    %   Copyright 2017-2020 The MathWorks, Inc.

    %#codegen

    if isa(currentScan.Ranges, 'single') || isa(referenceScan.Ranges, 'single')
        % The MEX file is compiled to expect double ranges and angles
        currentScan = lidarScan(double(currentScan.Ranges), double(currentScan.Angles));
        referenceScan = lidarScan(double(referenceScan.Ranges), double(referenceScan.Angles));
    end

    if coder.target('MATLAB')
        % When running in MATLAB, use MEX file for improved performance
        [relPose, score, covariance] = nav.algs.internal.mex.matchScansGrid(currentScan, referenceScan, ...
                                                          initialPoseAvailable, initialPose(:), maxRange, resolution, ...
                                                          linSearchRange, angSearchRange, maxLevel, computeCov);
    else
        % When generating code, use MATLAB implementation
        [relPose, score, covariance] = nav.algs.internal.impl.matchScansGrid(currentScan, referenceScan, ...
                                                          initialPoseAvailable, initialPose(:), maxRange, resolution, ...
                                                          linSearchRange, angSearchRange, maxLevel, computeCov);
    end

end
